import assert from 'assert';
import { readFileSync } from 'fs';
import { candidateConfirmPayload, candidateSearchPayload, fixPayload, reviewCounts, reviewReasonLabel, mediaTypeLabel, candidateTMDBURL, formatRuntime, formatTMDBRating, createRequestGate, createAsyncVisibilityGate, candidateStatus, scanLifecycleTransition, cacheEditorValue, floatingPopoverPosition } from './editor-state.js';

assert.deepStrictEqual(candidateSearchPayload('a.mkv', {'a.mkv': 'The Bureau'}, {'a.mkv': 'tv'}), {filename: 'a.mkv', title: 'The Bureau', media_type: 'tv'});
assert.strictEqual(reviewReasonLabel('identity_conflict'), 'відхилено автоматичну заміну ідентичності');
assert.deepStrictEqual(candidateConfirmPayload('a.mkv', {tmdb_id: 62476, media_type: 'tv'}), {filename: 'a.mkv', tmdb_id: 62476, media_type: 'tv'});
assert.deepStrictEqual(candidateSearchPayload('a.mkv', {}, {}, 'The Bureau'), {filename: 'a.mkv', title: '', media_type: 'auto'});
assert.deepStrictEqual(candidateSearchPayload('Ebigejl.2024.mkv', {}, {}, 'Любимые фильмы'), {filename: 'Ebigejl.2024.mkv', title: '', media_type: 'auto'});
assert.strictEqual(reviewReasonLabel('ambiguous_exact'), 'кілька близьких точних збігів');
assert.strictEqual(reviewReasonLabel('duplicate_tmdb_id'), 'один TMDB ID у різних фільмів');
assert.strictEqual(mediaTypeLabel('tv'), 'Серіал');
assert.strictEqual(candidateTMDBURL({media_type: 'tv', tmdb_id: 62476}), 'https://www.themoviedb.org/tv/62476');
assert.strictEqual(candidateTMDBURL({media_type: 'invalid', tmdb_id: 1}), '');
assert.strictEqual(formatRuntime(104), '1 год 44 хв');
assert.strictEqual(formatRuntime(14), '14 хв');
assert.match(formatTMDBRating(7.12, 250), /★ 7\.1/);
assert.deepStrictEqual(fixPayload(new Set(['a']), {a: 'Hint'}, {a: 'movie'}), [{filename: 'a', hint: 'Hint', media_type: 'movie'}]);
assert.deepStrictEqual(reviewCounts([{tmdb_id: 0, needs_review: true}, {tmdb_id: 2, needs_review: true}, {tmdb_id: 3}]), {unresolved: 1, suspicious: 1});
const gate = createRequestGate();
assert.strictEqual(gate.begin('a.mkv'), true);
assert.strictEqual(gate.begin('a.mkv'), false);
gate.end('a.mkv');
assert.strictEqual(gate.begin('a.mkv'), true);
const visibility = createAsyncVisibilityGate();
visibility.activate();
assert.strictEqual(visibility.isActive(), true);
visibility.deactivate();
assert.strictEqual(visibility.isActive(), false);
assert.deepStrictEqual(candidateStatus([]), {kind: 'empty', text: 'Нічого не знайдено'});
assert.strictEqual(candidateStatus(null, 'network').kind, 'error');
assert.strictEqual(candidateStatus([{}]).kind, 'ready');
assert.strictEqual(scanLifecycleTransition(false, 'scan-started'), true);
assert.strictEqual(scanLifecycleTransition(true, 'scan-finished'), false);
assert.strictEqual(scanLifecycleTransition(true, 'scan-progress'), true);
const cachedHints = {}, cachedTypes = {};
cacheEditorValue(cachedHints, 'a.mkv', 'Abigail');
cacheEditorValue(cachedTypes, 'a.mkv', 'movie');
assert.deepStrictEqual(candidateSearchPayload('a.mkv', cachedHints, cachedTypes), {filename: 'a.mkv', title: 'Abigail', media_type: 'movie'});
assert.deepStrictEqual(floatingPopoverPosition({left: 900, top: 700, bottom: 730}, {width: 430, height: 180}, {width: 1100, height: 800}), {left: 662, top: 514});
const editorCSS = readFileSync(new URL('./style.css', import.meta.url), 'utf8');
assert.match(editorCSS, /\.candidate-item\s*\{[^}]*grid-template-columns:\s*minmax\(0, 1fr\) 96px 64px/);
assert.match(editorCSS, /\.btn-refine-candidate\s*\{[^}]*width:\s*96px/);
console.log('frontend state tests passed');
