// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfirmTMDBCandidate(arg1) {
  return window['go']['main']['App']['ConfirmTMDBCandidate'](arg1);
}

export function DeleteMovie(arg1) {
  return window['go']['main']['App']['DeleteMovie'](arg1);
}

export function FixSelected(arg1) {
  return window['go']['main']['App']['FixSelected'](arg1);
}

export function GetAIModelCatalog() {
  return window['go']['main']['App']['GetAIModelCatalog']();
}

export function GetAIModels() {
  return window['go']['main']['App']['GetAIModels']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetEnvConfig() {
  return window['go']['main']['App']['GetEnvConfig']();
}

export function GetGrokModelCatalog() {
  return window['go']['main']['App']['GetGrokModelCatalog']();
}

export function GetGroqModelCatalog() {
  return window['go']['main']['App']['GetGroqModelCatalog']();
}

export function GetModelSelections() {
  return window['go']['main']['App']['GetModelSelections']();
}

export function GetMovies() {
  return window['go']['main']['App']['GetMovies']();
}

export function GetScanFolders() {
  return window['go']['main']['App']['GetScanFolders']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetTMDBCandidateDetails(arg1) {
  return window['go']['main']['App']['GetTMDBCandidateDetails'](arg1);
}

export function OpenGitHubPage() {
  return window['go']['main']['App']['OpenGitHubPage']();
}

export function OpenGitHubRepo() {
  return window['go']['main']['App']['OpenGitHubRepo']();
}

export function OpenGoogleSheet() {
  return window['go']['main']['App']['OpenGoogleSheet']();
}

export function OpenLogs() {
  return window['go']['main']['App']['OpenLogs']();
}

export function OpenSheet() {
  return window['go']['main']['App']['OpenSheet']();
}

export function OpenShowcase() {
  return window['go']['main']['App']['OpenShowcase']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function RepairMetadata(arg1) {
  return window['go']['main']['App']['RepairMetadata'](arg1);
}

export function RunScan() {
  return window['go']['main']['App']['RunScan']();
}

export function SaveEnvConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveEnvConfig'](arg1, arg2);
}

export function SearchTMDBCandidates(arg1) {
  return window['go']['main']['App']['SearchTMDBCandidates'](arg1);
}

export function SelectExcludedFolder() {
  return window['go']['main']['App']['SelectExcludedFolder']();
}

export function SelectMediaFolder() {
  return window['go']['main']['App']['SelectMediaFolder']();
}

export function SelectScanFolder() {
  return window['go']['main']['App']['SelectScanFolder']();
}

export function SetAIModels(arg1) {
  return window['go']['main']['App']['SetAIModels'](arg1);
}

export function SetExcludedFolders(arg1) {
  return window['go']['main']['App']['SetExcludedFolders'](arg1);
}

export function SetProviderModels(arg1, arg2) {
  return window['go']['main']['App']['SetProviderModels'](arg1, arg2);
}

export function SetScanFolders(arg1) {
  return window['go']['main']['App']['SetScanFolders'](arg1);
}

export function StopScan() {
  return window['go']['main']['App']['StopScan']();
}

export function SyncToCloud() {
  return window['go']['main']['App']['SyncToCloud']();
}

export function SyncToGitHub() {
  return window['go']['main']['App']['SyncToGitHub']();
}

export function UpdateMovie(arg1, arg2) {
  return window['go']['main']['App']['UpdateMovie'](arg1, arg2);
}
