// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteMovie(arg1) {
  return window['go']['main']['App']['DeleteMovie'](arg1);
}

export function FixSelected(arg1) {
  return window['go']['main']['App']['FixSelected'](arg1);
}

export function GetAIModels() {
  return window['go']['main']['App']['GetAIModels']();
}

export function GetMovies() {
  return window['go']['main']['App']['GetMovies']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function OpenLogs() {
  return window['go']['main']['App']['OpenLogs']();
}

export function OpenSheet() {
  return window['go']['main']['App']['OpenSheet']();
}

export function OpenShowcase() {
  return window['go']['main']['App']['OpenShowcase']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function RunScan() {
  return window['go']['main']['App']['RunScan']();
}

export function SelectMediaFolder() {
  return window['go']['main']['App']['SelectMediaFolder']();
}

export function StopScan() {
  return window['go']['main']['App']['StopScan']();
}

export function SyncToCloud() {
  return window['go']['main']['App']['SyncToCloud']();
}

export function UpdateMovie(arg1, arg2) {
  return window['go']['main']['App']['UpdateMovie'](arg1, arg2);
}
