// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';
import {context} from '../models';

export function DeleteMovie(arg1:string):Promise<void>;

export function FixSelected(arg1:Array<Record<string, any>>):Promise<void>;

export function GetAIModels():Promise<Array<string>>;

export function GetAppVersion():Promise<string>;

export function GetMovies():Promise<Array<storage.Movie>>;

export function GetStats():Promise<Record<string, any>>;

export function OpenLogs():Promise<void>;

export function OpenSheet():Promise<void>;

export function OpenShowcase():Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function RunScan():Promise<void>;

export function SelectMediaFolder():Promise<string>;

export function StopScan():Promise<void>;

export function SyncToCloud():Promise<void>;

export function UpdateMovie(arg1:context.Context,arg2:string,arg3:string):Promise<void>;
