// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {storage} from '../models';
import {tmdb} from '../models';

export function ConfirmTMDBCandidate(arg1:main.CandidateConfirmRequest):Promise<void>;

export function DeleteMovie(arg1:string):Promise<void>;

export function FixSelected(arg1:Array<main.FixRequest>):Promise<void>;

export function GetAIModelCatalog():Promise<main.AIModelCatalog>;

export function GetAIModels():Promise<Array<string>>;

export function GetAppVersion():Promise<string>;

export function GetMovies():Promise<Array<storage.Movie>>;

export function GetStats():Promise<Record<string, any>>;

export function GetTMDBCandidateDetails(arg1:main.CandidateConfirmRequest):Promise<tmdb.CandidateDetails>;

export function OpenGitHubPage():Promise<void>;

export function OpenGitHubRepo():Promise<void>;

export function OpenGoogleSheet():Promise<void>;

export function OpenLogs():Promise<void>;

export function OpenSheet():Promise<void>;

export function OpenShowcase():Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function RunScan():Promise<void>;

export function SearchTMDBCandidates(arg1:main.CandidateSearchRequest):Promise<Array<tmdb.TMDBCandidate>>;

export function SelectMediaFolder():Promise<string>;

export function SetAIModels(arg1:Array<string>):Promise<void>;

export function StopScan():Promise<void>;

export function SyncToCloud():Promise<void>;

export function SyncToGitHub():Promise<void>;

export function UpdateMovie(arg1:string,arg2:string):Promise<void>;
